### ISSUE TITLE
Smooth cape style does not work with More Banner Features

### ISSUE THREAD

**Issue by theelevinr** [tr7zw/WaveyCapes#50] opened 2023-10-29 14:31 UTC
When using the smooth cape style with a banner equipped in the trinkets cape slot with More Banner Features, both the smooth and blocky cape styles appear blocky. I can unfortunately not confirm whether this only occurs with a banner, since I do not own a cape in my account.

**Comment by tr7zw** [comment] 2023-10-29 20:18
Duplicate of #32

**Closed by tr7zw** 2023-10-29 20:18 UTC
